### ISSUE TITLE
Anmeldung session/admin gibt 202 zurück, wenn nicht superadmin aber trotzdem workspaces vorhanden

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-php#107]
session/admin
gibt 202 zurück, wenn zwar workspaces vorhanden aber kein superadmin-status

**Comment by paflov** [comment]
Sollte eigentlich nur sein, wenn keine workspaces und kein super-admin. Außerdem 204, nicht 202. Siehe: [hier](https://github.com/iqb-berlin/testcenter-iqb-php/issues/108).
 Werde ich fixen.
