### ISSUE TITLE
Keine Meldung bei falscher Passworteingabe in Anmeldescreen

### ISSUE THREAD

**Issue by kaestnti** [iqb-berlin/testcenter-iqb-php#109]
Bei der Eingabe falscher Credentials(Passwort und/oder Anmeldename) bei der Anmeldung kommt gar keine Meldung bzw passiert einfach nichts.
Eine Form von Fehlermeldung würde ich erwarten.

Interner Programmname: IQB-Testcenter
Programmversion: 2.0.0-beta.5 - 30.4.2020
Erforderliche Version der Server-Programmierung: 3.0.1

**Comment by kaestnti** [comment]
gleichermaßen kommt, wenn man z.B. Superadminrechte vergeben will und man dort das Passwort falsch eingibt, eine m.E. nach falsche Fehlermeldung  "Für dies Funktion haben sie keine Berechtigung:..." (siehe Screenshot)
![Fehler](https://user-images.githubusercontent.com/64467070/81721244-deec3180-947f-11ea-9b68-21b7790d096a.png)

**Comment by paflov** [comment]
@kaestnti Das ist ein Dublikat von dem hier oder? https://github.com/iqb-berlin/testcenter-iqb-ng/issues/136

**Comment by kaestnti** [comment]
Ja andersherum aber das andere hab ich nicht geschrieben. Du hast das doch da irgendwie hinkopiert oder?

**Comment by paflov** [comment]
eigentlich wollte ich nur verschieben, da es ein Frontend-Problem ist .. kA warum es stattdessen kopiert wurde. dann kann das hier ja weg.
