### ISSUE TITLE
customTexts

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-php#40]
Rückgabe der Login-Prozedur:
* typo: Der Rückgabeparameter heißt costumTexts statt customTexts
* wenn Logintoken schon vorhanden, werden beim Reload die customTexts nicht geliefert - nur beim ersten Login, bei dem erst ein token erzeugt wird

**Comment by paflov** [comment]
OK kann ich ja beim refactoren des Backends so umsetzen....

**Comment by paflov** [comment]
* type korriegert
* dublicates: https://github.com/iqb-berlin/testcenter-iqb-php/issues/53
