### ISSUE TITLE
Ist diese Datei deprecated?

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-php#44]
Soweit ich

[hier](https://github.com/iqb-berlin/testcenter-iqb-ng/blob/49a6a8fa6eb1e8846dbf4fd82a4274ec372e3987/src/app/test-controller/backend.service.ts#L57) 
sehen kann wird dieser [Endpoint](https://github.com/iqb-berlin/testcenter-iqb-php/blob/master/php_tc/getUnitData.php) gar nicht mehr verwendet, sondern [der hier](https://github.com/iqb-berlin/testcenter-iqb-php/blob/cdce6d7d3a3e2a3ab6858441d43498a76b825372/php_tc/tc_get.php#L135).

Die Datei kann getUnitData.php kann also ersatzlos gestrichen werden oder wird die aus irgendeinem bestimmten Grund aufgehoben?

**Comment by mechtelm** [comment]
Kann weg.
