### ISSUE TITLE
Wird hier der richtige Token geprüft?

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-php#45]
[Hier](https://github.com/iqb-berlin/testcenter-iqb-php/blob/cdce6d7d3a3e2a3ab6858441d43498a76b825372/php_tc/tc_get.php#L71) und [hier](https://github.com/iqb-berlin/testcenter-iqb-php/blob/cdce6d7d3a3e2a3ab6858441d43498a76b825372/php_tc/tc_get.php#L144) wird auf `$personToken` geprüft obwohl später nur noch `$loginToken` verwendet wird - hat das einen Sinn, oder sollte es eigentlich `$loginToken` heoßen - so wie [hier](https://github.com/iqb-berlin/testcenter-iqb-php/blob/cdce6d7d3a3e2a3ab6858441d43498a76b825372/php_tc/tc_get.php#L217).

**Comment by mechtelm** [comment]
Das loginToken dient nur solange als Authentifikation, bis ein personToken vergeben wurde. Ein booklet kann nur mit einem personToken geladen und bearbeitet werden. Wenn es keinen Personencode gibt (einstufige Anmeldung), dann wird "" als Personencode angenommen und trotzdem ein personToken generiert und vergeben. Insofern ist get('/resource/{resourceid}' nur für ein gültiges personToken erlaubt. Dass hier auf loginToken geprüft wird, ist ein Fehler.
Dass getWorkspaceId() mit dem loginToken erfolgt ist eine Performance-Entscheidung: Die DB-Tabelle mit den loginTokens liegt dichter an der Workspaces-Tabelle als die personToken-Tabelle.
