### ISSUE TITLE
Ist es absicht, das der reviewer nicht gespeichert wird?

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-php#46]
Beim speichern von Reviews wird kein Reviewer gespeichert, obwohl es eine solche Spalte gibt - sit das Absicht oder einfach ausgelassen worden? (Könnte ich jetzt leicht nachrüsten).
[Hier](https://github.com/iqb-berlin/testcenter-iqb-php/blob/cdce6d7d3a3e2a3ab6858441d43498a76b825372/vo_code/DBConnectionTC.php#L87) und [hier](https://github.com/iqb-berlin/testcenter-iqb-php/blob/cdce6d7d3a3e2a3ab6858441d43498a76b825372/vo_code/DBConnectionTC.php#L54).

**Comment by mechtelm** [comment]
Doch, der Reviewer muss gespeichert werden. Es gibt ja keinen Review ohne vorherige Anmeldung.

**Comment by paflov** [comment]
hat sich geklärt, war doch Absicht; reviewe rist klar durch test (booklet)-id
