### ISSUE TITLE
Warum wird hier das Label geupdatet?

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-php#47]
Der Fall, Test (Booklet) ist bereits gestartet, und wird noch mal gestartet (nach dem Neuladen und Klick auf "Zum Test zurückkehren" nehme ich an). An dieser Stelle wird das Label des Booklets überschrieben mit einem Label, das vom Frontend kommt:

https://github.com/iqb-berlin/testcenter-iqb-php/blob/cdce6d7d3a3e2a3ab6858441d43498a76b825372/vo_code/DBConnectionStart.php#L408

Macht das Sinn? Ändert sich das Label jemals ggü. dem, was in der XML spezifiziert ist (und damit schon beim ersten mal hinterlegt wurde)?

**Comment by mechtelm** [comment]
Soweit ich mich erinnere hatte ich das eingeführt, falls über eine geänderte XML-Datei der Booklet-Definition ein anderes Label gewünscht wird. Das hat es wohl mal gegeben. Andere Änderungen wären fatal, aber diese ist erlaubt.
