### ISSUE TITLE
syscheck: name fehlt

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-php#55]
https://ocba.iqb.hu-berlin.de/api/sys-checks gibt die Liste zurück, aber der name ist leer. Damit fehlt quasi die Id des syschecks. Vielleicht ist es auch besser, den Parameter in syscheckId umzubenennen.

**Comment by paflov** [comment]
Problem war: in der XML war keine ID vergeben!

ich verwende jetzt, da analog zu anderen XMLs die in der XML abgelegte IS, nicht mehr den Dateinamen. Wir sollten dann ID zum Pflichtfeld machen.
