### ISSUE TITLE
admin-login klappt nicht

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-php#56]
Der Login scheitert. Die Anmeldedaten sind ok (?), aber irgendeine nachfolgende Funktion scheitert (Zusammenstellen der workspace-Liste?). Ich werde aus dem php-Log nicht schlau.

**Comment by paflov** [comment]
Ursache war tatsächlich ein Unterschied im Verhalten von PostgreSQL im Gegensatz zu MySQL und SQLite - deswegen bin Datenbankagnostischen Anwednungen ggü. eigentlich immer skeptisch.
