### ISSUE TITLE
Nun doch kein Präfix beim Token?

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-php#85]
Zumindest beim Workspace-Admin läuft die Autorisierung nur ohne "a:"

**Comment by paflov** [comment]
Nö, hat sich dann doch als unnötig erwiesen.

**Comment by paflov** [comment]
Die BeispielToken fangen nur immer so an, damit der Tester beim Ausführen der automatischen Tests weiß gegen welches echte Token er ersetzen soll.

**Comment by mechtelm** [comment]
ok
