### ISSUE TITLE
get test rückgabewerte

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-php#86]
(ist das schon ein Test oder noch ein Booklet??)

label: string;
isEnabled: boolean;
statustxt: string;

**Comment by paflov** [comment]
es gibt denn endpoint?! [GET] /booklet

**Comment by mechtelm** [comment]
gut get booklet ist die Lösung, bitte dafür

label: string;
isEnabled: boolean;
statusText: string;

**Comment by mechtelm** [comment]
Nun noch eine Überlegung: Wenn ich in das Modul des Testcontrollers navigiere, dann muss er den Test laden - wenn es ihn noch nicht gibt, neu anlegen (also starten). Ist es denn dann sinnvoll zwischen GET Test (laden - schon gestartet) und PUT Test (starten und dann laden) zu unterscheiden? Ich möchte eigentlich nach Klicken auf den Start-Button nur navigieren.

**Comment by paflov** [comment]
Also, der Endpoint `[GET] /booklet/{booklet-name}/status` ging verloren bei der Spec-Compilierung, jetzt isser wieder da:
https://iqb-berlin.github.io/testcenter-iqb-php/#/paths/~1booklet~1{booklet_name}~1state/get

Nun müssen wir mal überlegen, was er genau liefern soll:

Aktuell das (taucht nicht alles in der Doku auf, vermutlich weil ich mir dachte, dass das noch eingedampft werden muss):

*  `canStart`: <bool>, -> drehe ich von mir aus um und mache isEnabled draus
*  `locked`:<bool> -> redundant?
*  `statusLabel`: "Zum Fortsetzen hier klicken" usw. -> ist das dein statusText? Würde ich hier eigentlich eher rausnehmen, finde eigentlich, diese Texte haben im backend nichts verloren
* `running`:<bool> -> sagt aus ob der Test bereits gestartet ist oder nicht

Und, wenn es bereits einen laufenden Test zu dieser Booklet/Person-Kombination gibt (theoretisch redundant mit "running"):
* `id`:<int> -> eine test-id
* `lastState`: du speicherst für laufende Booklets/units irgendwelche Key-Value-Paare weg, keine Ahnung wofür die genau sind ehrlich gesagt - hier kommt jedenfalls der Status des Tests wieder, wenn er bereits läuft. -> nicht nützlich?

---

Zu den anderen beiden Endpoints:

`[PUT] /test` Started den test und gibt die testId und den modus zurück - unabhängig oder der Test bereits vorher lief oder nicht. Es geht vom Booklet-Namen aus, den wir von als accessObject von `[GET] /session/person` bekommen haben.

`[GET] /test/{test-id}` wiederum gibt den eigentlichen *Inhalt*, namlich `'laststate', `locked`und `xml` des tests wieder.

Das ist auf jeden Fall semantisch nicht ganz sauber, man würde bei beiden Endpoints die selbe Art der Ausgabe erwarten. Demnach müssten beide Endpoints folgendes liefern:

* `laststate`
* `locked` bzw. `isEnbaled
* `xml`
* `mode`

und `[PUT] /test` noch zusätzlich

* `id`
einverstanden?

Im anderen Ticket hast du noch `lastUnit` gefordert - das ist Teil von laststate. Bisher kümmert sich das Backend nicht darum, was für key-Value-Paare da drin gespeichert werden, sondern speichert sie nur weg und gibt sie wieder aus. Das würde ich eigentlich gerne so lassen.

**Comment by paflov** [comment]
`[GET] /booklet/{booklet-name}/status` -> `[GET] /booklet/{booklet-name}`

* `label`
* `status`: locked / runing / pending / ...
* id und lastState kann weg

`[PUT] /test`
* id

`[GET] /test/{test-id}`
* xml
* mode
* laststate
* status

**Comment by mechtelm** [comment]
[PUT] /test/{booklet-name}
[GET] /test/..
kein Status
