### ISSUE TITLE
PUT test bitte nur ID

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-iqb-php#89]
Das Objekt { testId: string } ist unnötig, ich muss das extra wrappen

**Comment by paflov** [comment]
Hatte hin- und her überlegt ob ich die einzelne ID als Teil eines JSON-Objekts lasse oder plain zurück liefere und mich mit knapper Mehrheit für das erste entschieden, weil wir plain-antworten sonst nur bei Dateien etc. haben. Aber kanns auch gerne so machen.

**Comment by mechtelm** [comment]
Naja eilt nicht, habe das ja jetzt umgesetzt.

**Comment by paflov** [comment]
ah ich habs schon geändert Xd
