### ISSUE TITLE
[POST] /workspace/{ws_id}/file soll bei invalides XML 422 zurückgeben

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-iqb-php#93]
Beim Hochladen von invalidem XML soll statt `400` `422` zurück gegeben werden.

**Comment by mechtelm** [comment]
Dann aber bitte mit dem Fehlertext im Body, der durch php-parsing übergeben wurde (string)

**Comment by paflov** [comment]
ja, klar.
